### ISSUE TITLE
Feature Request: add support for extbase TranslationUtility

### ISSUE THREAD

**Issue by sventendo** [onigunn/intellij.xliff#3]
This could also be very useful for translating Flash Massages in a Controller context.

So this:
`$this->addFlashMessage('My flash message text');`

would become that:
`$this->addFlashMessage(LocalizationUtility::translate('my_flash_message', $this->extensionName));`

Ideally we could check for imported namespaces. Or we just use the full namespace:
`$this->addFlashMessage(\TYPO3\CMS\Extbase\Utility\LocalizationUtility::translate('my_flash_message', $this->extensionName));`

**Comment by onigunn** [comment]
Will look into this. I like the idea of having a context related functionality.

**Comment by onigunn** [comment]
Should be available soon in version 0.2.0 which is currently under review.
