### ISSUE TITLE
Feature Request: Inline ViewHelper style

### ISSUE THREAD

**Issue by ogrosko** [onigunn/intellij.xliff#5]
Would be great to have possibility to select between 
inline VH style
`{f:translate(key:'string')}`
or regular
`<f:translate key="string" />`

Or maybe additional VH from VHS ext. like:
`{v:l(key:'string')}`
or
`<v:l key="string" />`

**Comment by onigunn** [comment]
I don't intend to add support for the VHS VH, because needed functionality is provided by Fluid which is in the core now.

Question would be from a UX sight: Provide just another checkbox or introduce a second refactor action?

**Comment by ogrosko** [comment]
I think that checkbox would be great

**Comment by onigunn** [comment]
Will try to look into it this weekend. Should not be a big deal.

**Comment by onigunn** [comment]
Will be available in Version 0.2.0. Is now pending for Plugin review by Jetbrains.
